### ISSUE TITLE
Unable to create a stager in Chrome Ubuntu

### ISSUE THREAD

**Issue by m4nbat** [PhoenixC2/PhoenixC2#51]
# Description
I'm unsure whether its browser related, using Chrome Version 113.0.5672.92 (Official Build) (64-bit) on an Azure Ubuntu Linux VM but I'm unable to create a stager. It seems to just say a name is required but there is no option to do this in the UX.

# Reproduction
1. Go to 'Stagers' in menu
2. Click on 'Create a new stager'
3. Select the listener name
4. Then there is no option to select the type of stager or to input the name
5. Error message 'Name is required' occurs when you click create 

# Expected behavior
Ability to select stager type and name the stager available in the UX.

# Screenshots/Output (Optional)
![image](https://github.com/PhoenixC2/PhoenixC2/assets/16122365/baaeb778-243e-44a9-a5ac-f7f8d3b1dd82)

# Client Desktop:
 - OS: Azure Ubuntu Linux VM
 - Browser Chrome Version 113.0.5672.92 (Official Build) (64-bit)
 - Version of the Framework 1.01

**Comment by lucahennemann** [comment]
Hello Gavin, thank you for creating this issue. As I already stated in #50  , it will be fixed in the new release. I'm currently rewriting the frontend in react. If you still want to use the current version, you can use the Insomnia REST Client and import the insomnia.json from the root dir of the repository.
